export {katalog_data2}

const katalog_data2=[
    {
        "id": 46,
        "guid": "8e2d9464-337c-4a1a-8933-ac831ad78318",
        "name": "Бабочка матовая",
        "description": "Металл",
        "price": 47,
        "markup": 30,
        "cost_total": 61.1,
        "inStock": true,
        "katalogId":1,
        "katalogName":"Ручки",
        "colorName": "имя color",
        "brandName": "имя brand",
        "articleName": "имя article",
        "postavchik": "xl-01",
       
    },
    {
        "id": 48,
        "guid": "42e1c644-f915-4133-845a-f831c924c9c6",
        "name": "С15",
        "description": "Пластик",
        "price": 56,
        "markup": 30,
        "cost_total": 72.8,
        "inStock": true,
        "katalogId":1,
        "katalogName":"Ручки",
        "colorName": "имя color",
        "brandName": "имя brand",
        "articleName": "имя article",
        "postavchik": "xl-01",
       
    },
    {
        "id": 45,
        "guid": "0985a980-f766-491b-a55d-61081566aefe",
        "name": "С15 край ченый",
        "description": "Пластмасс ",
        "price": 48,
        "markup": 20,
        "cost_total": 57.6,
        "inStock": true,
        "katalogId":1,
        "katalogName":"Ручки",
        "colorName": "имя color",
        "brandName": "имя brand",
        "articleName": "имя article",
        "postavchik": "xl-01",
        
    },
    {
        "id": 47,
        "guid": "9a88936b-baea-47ea-bafb-8be1cdf8e628",
        "name": "Бабочка",
        "description": "Металл",
        "price": 47,
        "markup": 30,
        "cost_total": 61.1,
        "inStock": true,
        "katalogId":1,
        "katalogName":"Ручки",
        "colorName": "имя color",
        "brandName": "имя brand",
        "articleName": "имя article",
        "postavchik": "xl-01",
       
    },
    {
        "id": 50,
        "guid": "ba6eeb25-5e29-4ae1-8efe-1e641a77d33f",
        "name": "С17металик",
        "description": "Пластмасс 96 или 128",
        "price": 30,
        "markup": 30,
        "cost_total": 39,
        "inStock": true,
        "katalogId":1,
        "katalogName":"Ручки",
        "colorName": "имя color",
        "brandName": "имя brand",
        "articleName": "имя article",
        "postavchik": "xl-01",
      
    },
    {
        "id": 49,
        "guid": "3e537c98-61ac-4192-b279-3f576bffc150",
        "name": "С18 металик",
        "description": "Пластмасс ",
        "price": 57,
        "markup": 30,
        "cost_total": 74.1,
        "inStock": true,
        "katalogId":1,
        "katalogName":"Ручки",
        "colorName": "имя color",
        "brandName": "имя brand",
        "articleName": "имя article",
        "postavchik": "xl-01",
       
    },
    {
        "id": 51,
        "guid": "1673eeef-70c1-412b-8b16-efb15e6b90c1",
        "name": "С2390",
        "description": "Металл",
        "price": 176,
        "markup": 30,
        "cost_total": 228.8,
        "inStock": true,
        "katalogId":1,
        "katalogName":"Ручки",
        "colorName": "имя color",
        "brandName": "имя brand",
        "articleName": "имя article",
        "postavchik": "xl-01",
       
    },
    {
        "id": 54,
        "guid": "86abbf75-91bf-42ef-a82f-da47fca6c398",
        "name": "С24",
        "description": "Пластмасс ",
        "price": 20,
        "markup": 30,
        "cost_total": 26,
        "inStock": true,
        "katalogId":1,
        "katalogName":"Ручки",
        "colorName": "имя color",
        "brandName": "имя brand",
        "articleName": "имя article",
        "postavchik": "xl-01",
       
    },
    {
        "id": 52,
        "guid": "264d5817-3d5d-41a1-807f-97e840503c42",
        "name": "С42",
        "description": "Пластмасс ",
        "price": 35,
        "markup": 30,
        "cost_total": 45.5,
        "katalogId":1,
        "katalogName":"Ручки",
        "colorName": "имя color",
        "brandName": "имя brand",
        "articleName": "имя article",
        "postavchik": "xl-01",
        
    },
    {
        "id": 60,
        "guid": "7b520988-7af5-4ad3-bd49-b8c20fd8eaae",
        "name": "R74",
        "description": "",
        "price": 112,
        "markup": 30,
        "cost_total": 145.6,
        "inStock": true,
        "katalogId":1,
        "katalogName":"Ручки",
        "colorName": "имя color",
        "brandName": "имя brand",
        "articleName": "имя article",
        "postavchik": "xl-01",
        
    },
    {
        "id": 59,
        "guid": "2d30558e-ae4e-42f9-b014-284ffeebd35d",
        "name": "РЕЛИНГ",
        "description": "Металл",
        "price": 112,
        "markup": 30,
        "cost_total": 145.6,
        "inStock": true,
        "katalogId":1,
        "katalogName":"Ручки",
        "colorName": "имя color",
        "brandName": "имя brand",
        "articleName": "имя article",
        "postavchik": "xl-01",
       
    }
]