export {katalog_data}

const katalog_data= [
  {
    id: 46,
    name: 'Бабочка матовая',
    description: 'Металл',
    price: 47,
    markup: 30,
    guid: '8e2d9464-337c-4a1a-8933-ac831ad78318',
    position: 0,
    hidden: false,
    katalogId: 1,
    colorId: 2,
    brandId: 1,
    articleId: 2,
    postavchikId: 1,
    inStock: true,
    sale: false,
    katalog: null,
    color: null,
    brand: null,
    article: null,
    postavchik: null,
    productNomenclatures: [],
  },
  {
    id: 48,
    name: 'С15',
    description: 'Пластик',
    price: 56,
    markup: 30,
    guid: '42e1c644-f915-4133-845a-f831c924c9c6',
    position: 0,
    hidden: false,
    katalogId: 1,
    colorId: 2,
    brandId: 1,
    articleId: 4,
    postavchikId: 1,
    inStock: true,
    sale: false,
    katalog: null,
    color: null,
    brand: null,
    article: null,
    postavchik: null,
    productNomenclatures: [],
  },
  {
    id: 45,
    name: 'С15 край ченый',
    description: 'Пластмасс ',
    price: 48,
    markup: 20,
    guid: '0985a980-f766-491b-a55d-61081566aefe',
    position: 0,
    hidden: false,
    katalogId: 1,
    colorId: 2,
    brandId: 1,
    articleId: 4,
    postavchikId: 1,
    inStock: true,
    sale: false,
    katalog: null,
    color: null,
    brand: null,
    article: null,
    postavchik: null,
    productNomenclatures: [],
  },
  {
    id: 47,
    name: 'Бабочка',
    description: 'Металл',
    price: 47,
    markup: 30,
    guid: '9a88936b-baea-47ea-bafb-8be1cdf8e628',
    position: 0,
    hidden: false,
    katalogId: 1,
    colorId: 3,
    brandId: 1,
    articleId: 2,
    postavchikId: 1,
    inStock: true,
    sale: false,
    katalog: null,
    color: null,
    brand: null,
    article: null,
    postavchik: null,
    productNomenclatures: [],
  },
  {
    id: 50,
    name: 'С17металик',
    description: 'Пластмасс 96 или 128',
    price: 30,
    markup: 30,
    guid: 'ba6eeb25-5e29-4ae1-8efe-1e641a77d33f',
    position: 0,
    hidden: false,
    katalogId: 1,
    colorId: 3,
    brandId: 1,
    articleId: 2,
    postavchikId: 1,
    inStock: true,
    sale: false,
    katalog: null,
    color: null,
    brand: null,
    article: null,
    postavchik: null,
    productNomenclatures: [],
  },
  {
    id: 49,
    name: 'С18 металик',
    description: 'Пластмасс ',
    price: 57,
    markup: 30,
    guid: '3e537c98-61ac-4192-b279-3f576bffc150',
    position: 0,
    hidden: false,
    katalogId: 1,
    colorId: 6,
    brandId: 1,
    articleId: 4,
    postavchikId: 1,
    inStock: true,
    sale: false,
    katalog: null,
    color: null,
    brand: null,
    article: null,
    postavchik: null,
    productNomenclatures: [],
  },
  {
    id: 51,
    name: 'С2390',
    description: 'Металл',
    price: 176,
    markup: 30,
    guid: '1673eeef-70c1-412b-8b16-efb15e6b90c1',
    position: 0,
    hidden: false,
    katalogId: 1,
    colorId: 7,
    brandId: 1,
    articleId: 3,
    postavchikId: 1,
    inStock: true,
    sale: false,
    katalog: null,
    color: null,
    brand: null,
    article: null,
    postavchik: null,
    productNomenclatures: [],
  },
  {
    id: 54,
    name: 'С24',
    description: 'Пластмасс ',
    price: 20,
    markup: 30,
    guid: '86abbf75-91bf-42ef-a82f-da47fca6c398',
    position: 0,
    hidden: false,
    katalogId: 1,
    colorId: 8,
    brandId: 1,
    articleId: 3,
    postavchikId: 1,
    inStock: true,
    sale: false,
    katalog: null,
    color: null,
    brand: null,
    article: null,
    postavchik: null,
    productNomenclatures: [],
  },
  {
    id: 52,
    name: 'С42',
    description: 'Пластмасс ',
    price: 35,
    markup: 30,
    guid: '264d5817-3d5d-41a1-807f-97e840503c42',
    position: 0,
    hidden: false,
    katalogId: 1,
    colorId: 8,
    brandId: 1,
    articleId: 3,
    postavchikId: 1,
    inStock: false,
    sale: false,
    katalog: null,
    color: null,
    brand: null,
    article: null,
    postavchik: null,
    productNomenclatures: [],
  },
  {
    id: 60,
    name: 'R74',
    description: '',
    price: 112,
    markup: 30,
    guid: '7b520988-7af5-4ad3-bd49-b8c20fd8eaae',
    position: 0,
    hidden: false,
    katalogId: 1,
    colorId: 8,
    brandId: 1,
    articleId: 4,
    postavchikId: 1,
    inStock: true,
    sale: false,
    katalog: null,
    color: null,
    brand: null,
    article: null,
    postavchik: null,
    productNomenclatures: [],
  },
  {
    id: 59,
    name: 'РЕЛИНГ',
    description: 'Металл',
    price: 112,
    markup: 30,
    guid: '2d30558e-ae4e-42f9-b014-284ffeebd35d',
    position: 0,
    hidden: false,
    katalogId: 1,
    colorId: 8,
    brandId: 1,
    articleId: 4,
    postavchikId: 1,
    inStock: true,
    sale: false,
    katalog: null,
    color: null,
    brand: null,
    article: null,
    postavchik: null,
    productNomenclatures: [],
  },
];
